packages:
  - variant-a-feature-based
  - variant-b-clean
  - e2e

allowBuilds:
  "@prisma/engines": true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - jsdom@30.0.1
